name: Monitor FIBOS Node Status

on:
  schedule:
    # 修改 Cron 表达式: '0 */12 * * *' 表示每12小时运行一次（在第0分钟）
    # 例如，在 00:00 和 12:00 运行
    - cron: '0 */12 * * *' 
  workflow_dispatch:

jobs:
  check-and-notify:
    runs-on: ubuntu-latest
    
    env:
      # --- 基础配置 ---
      NODE_NAMES: "fibos123comm,chainmoefibo"
      RECIPIENT_EMAIL: "bp@fibos123.com"
      
      # --- FIBOS API 配置 ---
      API_URL: "https://bp.fibos.io/1.0/app/data/live"

      # --- SMTP 服务器配置 ---
      SMTP_SERVER: "smtp.gmail.com"
      SMTP_PORT: "465"

      # --- 邮件内容自定义 ---
      MAIL_FROM_NAME: "FIBOS 节点监控机器人" 
      MAIL_SUBJECT: "警报：FIBOS 节点 [{abnormal_nodes}] 状态异常"
      MAIL_BODY_TEMPLATE: |
        尊敬的管理员：
        
        系统检测到以下您所监控的 FIBOS 节点状态异常:
        
        节点列表: {abnormal_nodes}
        
        请尽快登录服务器进行检查。
        
        详情请访问: https://bp.fibos.io/#/live
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python and cache dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          # 启用 pip 缓存
          cache: 'pip'
          # 告诉 action 根据这个文件的哈希值来创建或恢复缓存
          # 确保 requirements.txt 文件在你的仓库根目录
          cache-dependency-path: 'requirements.txt'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Python Monitor Script
        run: python monitor_and_notify.py
        env:
          MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}